-- MySQL Script generated by MySQL Workbench
-- Fri Jul  9 16:48:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `IsApproved` INT NOT NULL,
  `Balance` DOUBLE NOT NULL,
  `Type` INT NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Listing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Listing` (
  `idListing` INT NOT NULL,
  `IsApproved` INT NOT NULL,
  `Type` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `SurfaceArea` INT NOT NULL,
  `NumberOfRooms` INT NOT NULL,
  `NumberOfBeds` INT NOT NULL,
  `DetailedDescription` VARCHAR(255) NOT NULL,
  `Image` VARCHAR(255) NOT NULL,
  `PricePerNight` FLOAT NOT NULL,
  `Discount` INT NOT NULL,
  `AC` TINYINT NOT NULL,
  `WiFi` TINYINT NOT NULL,
  `Parking` TINYINT NOT NULL,
  `Kitchen` TINYINT NOT NULL,
  `TV` TINYINT NOT NULL,
  `Garden` TINYINT NOT NULL,
  `Balcony` TINYINT NOT NULL,
  `Smoking` TINYINT NOT NULL,
  `Pets` TINYINT NOT NULL,
  `idUser` INT NOT NULL,
  `OnlinePayment` TINYINT NOT NULL,
  PRIMARY KEY (`idListing`),
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `idReservation` INT NOT NULL,
  `CheckIn` DATETIME NOT NULL,
  `CheckOut` DATETIME NOT NULL,
  `idListing` INT NOT NULL,
  `idUser` INT NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Rating` INT NOT NULL,
  `IsPaid` TINYINT NOT NULL,
  `Reservationcol1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReservation`),
  INDEX `idListing_idx` (`idListing` ASC) VISIBLE,
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `idListing`
    FOREIGN KEY (`idListing`)
    REFERENCES `mydb`.`Listing` (`idListing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUserr`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
